// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ4jQx-sdAi2PegM0docwbgiKRSdYXayY',
    appId: '1:814505040139:web:3506f7c4d351d66115aa0e',
    messagingSenderId: '814505040139',
    projectId: 'logins-a7218',
    authDomain: 'logins-a7218.firebaseapp.com',
    storageBucket: 'logins-a7218.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlH1XZyKPROZrj2ttGiqfTvbRVIaNfFG8',
    appId: '1:814505040139:android:00b5b509768685fe15aa0e',
    messagingSenderId: '814505040139',
    projectId: 'logins-a7218',
    storageBucket: 'logins-a7218.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP5-D6u5DC-dkZqIeQlmK3KcVk51WG5ak',
    appId: '1:814505040139:ios:51da7f758a1334fa15aa0e',
    messagingSenderId: '814505040139',
    projectId: 'logins-a7218',
    storageBucket: 'logins-a7218.appspot.com',
    iosBundleId: 'com.example.tobetoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAP5-D6u5DC-dkZqIeQlmK3KcVk51WG5ak',
    appId: '1:814505040139:ios:65089779d4867c5415aa0e',
    messagingSenderId: '814505040139',
    projectId: 'logins-a7218',
    storageBucket: 'logins-a7218.appspot.com',
    iosBundleId: 'com.example.tobetoApp.RunnerTests',
  );
}
